site_name: 小红书电商 Python SDK 文档
site_description: 小红书(XiaoHongShu)电商平台 Python SDK 官方文档
site_author: andersonby
site_url: https://your-domain.com

repo_name: xiaohongshu-ecommerce-python-sdk
repo_url: https://github.com/your-username/xiaohongshu-ecommerce-python-sdk

theme:
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: pink
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: pink
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

plugins:
  - search:
      lang: zh
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            show_root_heading: true
            show_root_full_path: false
            show_object_full_path: false
            show_category_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            group_by_category: true
            heading_level: 2
            members_order: source
            docstring_section_style: table
            signature_crossrefs: true
            separate_signature: true

nav:
  - 首页: index.md
  - 快速开始: quickstart.md
  - API 参考:
    - 客户端总览: api/client.md
    - 认证授权: api/oauth.md
    - 公共服务: api/common.md
    - 商品管理: api/product.md
    - 订单管理: api/order.md
    - 售后服务: api/after_sale.md
    - 库存管理: api/inventory.md
    - 财务管理: api/finance.md
    - 物流快递: api/express.md
    - 包裹管理: api/package.md
    - 素材中心: api/material.md
    - 即时零售: api/instant_shopping.md
    - 精品模式: api/boutique.md
    - 电子发票: api/invoice.md
    - 配送券: api/delivery_voucher.md
    - 数据安全: api/data.md
  - 示例代码: examples.md
  - 更新日志: changelog.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-username/xiaohongshu-ecommerce-python-sdk
  version:
    provider: mike