name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install PDM
        run: pipx install pdm

      - name: Configure PDM to use uv
        run: pdm config use_uv true

      - name: Cache PDM venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-pdm-uv-venv-${{ hashFiles('pdm.lock') }}
          restore-keys: |
            ${{ runner.os }}-pdm-uv-venv-

      - name: Cache uv cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-cache-${{ hashFiles('pdm.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-cache-

      - name: Install dependencies
        run: pdm install -G dev -v

      - name: Run tests
        run: pdm run pytest
